In [1]:
import pandas as pd

obj_value_df = pd.DataFrame(columns = ['obj_value_avg_1', 'obj_value_het_1', 'obj_value_avg_2', 'obj_value_het_2', 'obj_value_avg_3', 'obj_value_het_3'])
obj_value_better_df = pd.DataFrame(columns = ['obj_value_avg_1', 'obj_value_het_1', 'obj_value_avg_2', 'obj_value_het_2', 'obj_value_avg_3', 'obj_value_het_3'])
avg_work_day_sim = []
improved_weeks_sim = []

In [2]:
data_ori = pd.read_excel("ICU_avg_effect.xlsx", sheet_name = "Old Schedule")
data_ori

,weeknum,index,status,surgeon,weekday,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,0,1,0,5,3,NaN,NaN,0,elective,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,2,0,5,3,NaN,NaN,1,urgent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,3,0,1,3,NaN,NaN,2 or 3,emergent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,4,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,5,0,5,4,NaN,NaN,smooth surgeon's workload across days,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5344,208,27,1,5,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5345,208,28,0,3,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5346,208,29,2,3,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5347,208,30,2,3,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5348,208,31,1,8,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
import multiprocessing
from ipynb.fs.full.simulation_worker import urgent_smooth
from ipynb.fs.full.simulation_worker import cal_obj1_urgent
from ipynb.fs.full.simulation_worker import mono_check
from ipynb.fs.full.simulation_worker import elective_smooth
from ipynb.fs.full.simulation_worker import cal_obj1
from ipynb.fs.full.simulation_worker import cal_obj2
from ipynb.fs.full.simulation_worker import additional_day
from ipynb.fs.full.simulation_worker import schedule_es
from ipynb.fs.full.simulation_worker import objective_cal
from ipynb.fs.full.simulation_worker import worker

In [ ]:
frac = 0.5 # fraction of the urgent cases to be considered as unknown in the first place

with multiprocessing.Pool(processes = 5) as pool:
    results = [
        pool.apply_async(
            worker, 
            args = (data_ori, obj_value_df, obj_value_better_df, avg_work_day_sim, improved_weeks_sim, frac)
        ) 
        for _ in range(5)
    ]
    output = [r.get() for r in results]
output

100%|██████████| 20/20 [42:09<00:00, 126.50s/it]
100%|██████████| 20/20 [42:25<00:00, 127.26s/it]
100%|██████████| 20/20 [42:31<00:00, 127.56s/it]
100%|██████████| 20/20 [42:40<00:00, 128.02s/it]
100%|██████████| 20/20 [42:52<00:00, 128.64s/it]

[(    obj_value_avg_1  obj_value_het_1  obj_value_avg_2  obj_value_het_2  \
  0          4221.945         4295.043        10290.411         8161.425
  1          4231.045         4292.323        10312.591         8280.195
  2          4234.685         4297.999        10321.463         8270.565
  3          4209.205         4283.917        10259.359         8121.300
  4          4218.305         4291.837        10281.539         8150.190
  5          4229.225         4299.935        10308.155         8196.735
  6          4259.255         4333.177        10381.349         8232.045
  7          4247.425         4319.575        10352.515         8222.415
  8          4262.895         4329.353        10390.221         8302.665
  9          4278.365         4344.451        10427.927         8337.975
  10         4270.175         4333.295        10407.965         8346.000
  11         4212.845         4277.053        10268.231         8217.600
  12         4219.215         4287.081        10283.757         8199.945
  13         4239.235         4313.929        10332.553         8183.895
  14         4234.685         4308.069        10321.463         8185.500
  15         4209.205         4289.617        10259.359         8073.150
  16         4261.985         4329.169        10388.003         8294.640
  17         4213.755         4278.187        10270.449         8217.600
  18         4264.715         4332.761        10394.657         8293.035
  19         4229.225         4298.795        10308.155         8206.365

      obj_value_avg_3  obj_value_het_3
  0         10819.314         8374.995
  1         10842.634         8496.873
  2         10851.962         8486.991
  3         10786.666         8333.820
  4         10809.986         8363.466
  5         10837.970         8411.229
  6         10914.926         8447.463
  7         10884.610         8437.581
  8         10924.254         8519.931
  9         10963.898         8556.165
  10        10942.910         8564.400
  11        10795.994         8432.640
  12        10812.318         8414.523
  13        10863.622         8398.053
  14        10851.962         8399.700
  15        10786.666         8284.410
  16        10921.922         8511.696
  17        10798.326         8432.640
  18        10928.918         8510.049
  19        10837.970         8421.111  ,
      obj_value_avg_1  obj_value_het_1  obj_value_avg_2  obj_value_het_2  \
  0          3915.275         4021.755         9542.945         7156.695
  1          3916.185         4017.563         9545.163         7208.055
  2          3911.635         4017.587         9534.073         7143.855
  3          3928.015         4033.059         9573.997         7182.375
  4          3902.535         4011.199         9511.893         7100.520
  5          3941.665         4047.789         9607.267         7224.105
  6          3928.925         4034.395         9576.215         7195.215
  7          3925.285         4033.849         9567.343         7142.250
  8          3948.035         4053.459         9622.793         7222.500
  9          3928.925         4034.757         9576.215         7159.905
  10         3951.675         4054.569         9631.665         7262.625
  11         3916.185         4018.507         9545.163         7167.930
  12         3914.365         4020.223         9540.727         7147.065
  13         3942.575         4049.113         9609.485         7188.795
  14         3899.805         4003.237         9505.239         7167.930
  15         3932.565         4042.345         9585.087         7142.250
  16         3947.125         4050.033         9620.575         7230.525
  17         3894.345         4000.221         9491.931         7121.385
  18         3928.925         4034.573         9576.215         7179.165
  19         3930.745         4031.135         9580.651         7232.130

      obj_value_avg_3  obj_value_het_3
  0         10033.430         7343.973
  1         10035.762         7396.677
  2         10024.102         7330.797
  3         10066.078         7370.325
  4         10000.782         7286.328
  5         10101.058         7413.147
  6         10068.410         7383.501
  7         10059.082         7329.150
  8         10117.382         7411.500
  9         10068.410         7347.267
  10        10126.710         7452.675
  11        10035.762         7355.502
  12        10031.098         7334.091
  13        10103.390         7376.913
  14         9993.786         7355.502
  15        10077.738         7329.150
  16        10115.050         7419.735
  17         9979.794         7307.739
  18        10068.410         7367.031
  19        10073.074         7421.382  ,
  [2.633047210300429,
   2.618271954674221,
   2.653486700215672,
   2.6327845382963493,
   2.6432664756446993,
   2.6402877697841727,
   2.627324749642346,
   2.6061036195883607,
   2.631200575125809,
   2.6216022889842634,
   2.6081370449678802,
   2.6539842067480257,
   2.6489208633093524,
   2.644396551724138,
   2.5825174825174826,
   2.6136363636363638,
   2.6153846153846154,
   2.636947218259629,
   2.6431146359048308,
   2.620443173695497],
  [83,
   86,
   91,
   91,
   92,
   90,
   84,
   89,
   78,
   79,
   82,
   94,
   83,
   78,
   91,
   85,
   77,
   85,
   84,
   88]),
 (    obj_value_avg_1  obj_value_het_1  obj_value_avg_2  obj_value_het_2  \
  0          4182.815         4255.591        10195.037         8082.780
  1          4224.675         4291.605        10297.065         8219.205
  2          4296.565         4350.221        10472.287         8480.820
  3          4218.305         4291.267        10281.539         8155.005
  4          4201.015         4279.221        10239.397         8074.755
  5          4188.275         4259.735        10208.345         8105.250
  6          4289.285         4355.969        10454.543         8355.630
  7          4251.975         4321.445        10363.605         8254.515
  8          4230.135         4297.459        10310.373         8227.230
  9          4282.915         4351.831        10439.017         8323.530
  10         4312.035         4376.529        10509.993         8421.435
  11         4271.995         4346.963        10412.401         8249.700
  12         4199.195         4276.383        10234.961         8079.570
  13         4233.775         4305.985        10319.245         8193.525
  14         4235.595         4301.793        10323.681         8248.095
  15         4303.845         4370.883        10490.031         8382.915
  16         4292.015         4353.671        10461.197         8403.780
  17         4220.125         4292.585        10285.975         8163.030
  18         4216.485         4280.069        10277.103         8230.440
  19         4284.735         4348.399        10443.453         8371.680

      obj_value_avg_3  obj_value_het_3
  0         10719.038         8294.292
  1         10826.310         8434.287
  2         11010.538         8702.748
  3         10809.986         8368.407
  4         10765.678         8286.057
  5         10733.030         8317.350
  6         10991.882         8574.282
  7         10896.270         8470.521
  8         10840.302         8442.522
  9         10975.558         8541.342
  10        11050.182         8641.809
  11        10947.574         8465.580
  12        10761.014         8290.998
  13        10849.630         8407.935
  14        10854.294         8463.933
  15        11029.194         8602.281
  16        10998.878         8623.692
  17        10814.650         8376.642
  18        10805.322         8445.816
  19        10980.222         8590.752  ,
      obj_value_avg_1  obj_value_het_1  obj_value_avg_2  obj_value_het_2  \
  0          3924.375         4029.289         9565.125         7179.165
  1          3921.645         4025.323         9558.471         7169.535
  2          3929.835         4036.093         9578.433         7211.265
  3          3925.285         4029.853         9567.343         7175.955
  4          3924.375         4033.077         9565.125         7155.090
  5          3906.175         4007.179         9520.765         7167.930
  6          3922.555         4026.451         9560.689         7192.005
  7          3932.565         4034.745         9585.087         7192.005
  8          3932.565         4034.751         9585.087         7211.265
  9          3924.375         4032.525         9565.125         7169.535
  10         3960.775         4064.205         9653.845         7275.465
  11         3933.475         4044.055         9587.305         7150.275
  12         3900.715         4009.881         9507.457         7127.805
  13         3920.735         4030.453         9556.253         7142.250
  14         3929.835         4034.009         9578.433         7182.375
  15         3952.585         4058.927         9633.883         7232.130
  16         3938.025         4044.019         9598.395         7193.610
  17         3914.365         4023.281         9540.727         7131.015
  18         3914.365         4016.815         9540.727         7185.585
  19         3935.295         4037.007         9591.741         7201.635

      obj_value_avg_3  obj_value_het_3
  0         10056.750         7367.031
  1         10049.754         7357.149
  2         10070.742         7399.971
  3         10059.082         7363.737
  4         10056.750         7342.326
  5         10010.110         7355.502
  6         10052.086         7380.207
  7         10077.738         7380.207
  8         10077.738         7399.971
  9         10056.750         7357.149
  10        10150.030         7465.851
  11        10080.070         7337.385
  12         9996.118         7314.327
  13        10047.422         7329.150
  14        10070.742         7370.325
  15        10129.042         7421.382
  16        10091.730         7381.854
  17        10031.098         7317.621
  18        10031.098         7373.619
  19        10084.734         7390.089  ,
  [2.6421952957947257,
   2.6295503211991433,
   2.6051502145922747,
   2.6285919540229883,
   2.6551475881929445,
   2.6291814946619216,
   2.6221264367816093,
   2.5912305516265914,
   2.6464646464646466,
   2.608291636883488,
   2.6195965417867435,
   2.653179190751445,
   2.6379928315412187,
   2.6139105748757983,
   2.6446043165467628,
   2.640988372093023,
   2.593727726300784,
   2.6284697508896797,
   2.636039886039886,
   2.6140602582496415],
  [93,
   89,
   84,
   84,
   93,
   91,
   89,
   85,
   81,
   80,
   80,
   84,
   99,
   89,
   83,
   82,
   81,
   92,
   82,
   83]),
 (    obj_value_avg_1  obj_value_het_1  obj_value_avg_2  obj_value_het_2  \
  0          4272.905         4334.987        10414.619         8360.445
  1          4243.785         4307.819        10343.643         8283.405
  2          4245.605         4312.557        10348.079         8262.540
  3          4240.145         4316.583        10334.771         8171.055
  4          4241.965         4318.471        10339.207         8174.265
  5          4245.605         4312.557        10348.079         8262.540
  6          4256.525         4319.895        10374.695         8315.505
  7          4254.705         4323.517        10370.259         8265.750
  8          4238.325         4315.075        10330.335         8164.635
  9          4224.675         4290.655        10297.065         8227.230
  10         4228.315         4301.651        10305.937         8172.660
  11         4257.435         4322.169        10376.913         8305.875
  12         4237.415         4306.151        10328.117         8230.440
  13         4255.615         4323.321        10372.477         8276.985
  14         4298.385         4359.329        10476.723         8423.040
  15         4340.245         4402.563        10578.751         8498.475
  16         4211.935         4285.229        10266.013         8138.955
  17         4241.055         4314.487        10336.989         8198.340
  18         4289.285         4349.129        10454.543         8413.410
  19         4206.475         4280.705        10252.705         8119.695

      obj_value_avg_3  obj_value_het_3
  0         10949.906         8579.223
  1         10875.282         8500.167
  2         10879.946         8478.756
  3         10865.954         8384.877
  4         10870.618         8388.171
  5         10879.946         8478.756
  6         10907.930         8533.107
  7         10903.266         8482.050
  8         10861.290         8378.289
  9         10826.310         8442.522
  10        10835.638         8386.524
  11        10910.262         8523.225
  12        10858.958         8445.816
  13        10905.598         8493.579
  14        11015.202         8643.456
  15        11122.474         8720.865
  16        10793.662         8351.937
  17        10868.286         8412.876
  18        10991.882         8633.574
  19        10779.670         8332.173  ,
      obj_value_avg_1  obj_value_het_1  obj_value_avg_2  obj_value_het_2  \
  0          3921.645         4025.875         9558.471         7171.140
  1          3913.455         4011.311         9538.509         7203.240
  2          3928.015         4036.835         9573.997         7159.905
  3          3917.095         4028.571         9547.381         7126.200
  4          3922.555         4027.395         9560.689         7172.745
  5          3923.465         4027.015         9562.907         7190.400
  6          3946.215         4046.815         9618.357         7233.735
  7          3919.825         4022.093         9554.035         7192.005
  8          3938.935         4042.303         9600.613         7201.635
  9          3922.555         4021.131         9560.689         7188.795
  10         3907.995         4015.723         9525.201         7139.040
  11         3921.645         4025.507         9558.471         7180.770
  12         3932.565         4035.885         9585.087         7203.240
  13         3931.655         4036.657         9582.869         7195.215
  14         3941.665         4043.609         9607.267         7228.920
  15         3949.855         4052.877         9627.229         7228.920
  16         3897.985         4006.669         9500.803         7114.965
  17         3918.915         4025.905         9551.817         7145.460
  18         3921.645         4028.167         9558.471         7139.040
  19         3913.455         4019.861         9538.509         7156.695

      obj_value_avg_3  obj_value_het_3
  0         10049.754         7358.796
  1         10028.766         7391.736
  2         10066.078         7347.267
  3         10038.094         7312.680
  4         10052.086         7360.443
  5         10054.418         7378.560
  6         10112.718         7423.029
  7         10045.090         7380.207
  8         10094.062         7390.089
  9         10052.086         7376.913
  10        10014.774         7325.856
  11        10049.754         7368.678
  12        10077.738         7391.736
  13        10075.406         7383.501
  14        10101.058         7418.088
  15        10122.046         7418.088
  16         9989.122         7301.151
  17        10042.758         7332.444
  18        10049.754         7325.856
  19        10028.766         7343.973  ,
  [2.619557458957887,
   2.661115133960898,
   2.655890804597701,
   2.645369705671213,
   2.617961511047755,
   2.6284896206156048,
   2.663761801016703,
   2.6523947750362846,
   2.6406585540443808,
   2.626876340243031,
   2.616642958748222,
   2.6284074605451937,
   2.6331658291457285,
   2.6207142857142856,
   2.612857142857143,
   2.6319595083152567,
   2.6324054246966453,
   2.603827072997874,
   2.6191155492154063,
   2.6226012793176974],
  [89,
   88,
   84,
   90,
   95,
   82,
   79,
   91,
   77,
   85,
   94,
   87,
   87,
   82,
   86,
   77,
   87,
   83,
   84,
   88]),
 (    obj_value_avg_1  obj_value_het_1  obj_value_avg_2  obj_value_het_2  \
  0          4251.065         4321.831        10361.387         8241.675
  1          4222.855         4296.747        10292.629         8156.610
  2          4320.225         4384.075        10529.955         8443.905
  3          4203.745         4272.553        10246.051         8159.820
  4          4262.895         4329.543        10390.221         8301.060
  5          4268.355         4342.997        10403.529         8244.885
  6          4258.345         4322.733        10379.131         8310.690
  7          4230.135         4296.699        10310.373         8233.650
  8          4301.115         4362.731        10483.377         8423.040
  9          4220.125         4295.245        10285.975         8140.560
  10         4201.925         4281.115        10241.615         8068.335
  11         4218.305         4283.097        10281.539         8224.020
  12         4288.375         4356.355        10452.325         8342.790
  13         4239.235         4309.939        10332.553         8217.600
  14         4239.235         4305.949        10332.553         8251.305
  15         4316.585         4379.919        10521.083         8440.695
  16         4186.455         4259.557        10203.909         8087.595
  17         4216.485         4286.529        10277.103         8175.870
  18         4274.725         4343.905        10419.055         8304.270
  19         4247.425         4317.675        10352.515         8238.465

      obj_value_avg_3  obj_value_het_3
  0         10893.938         8457.345
  1         10821.646         8370.054
  2         11071.170         8664.867
  3         10772.674         8373.348
  4         10924.254         8518.284
  5         10938.246         8460.639
  6         10912.594         8528.166
  7         10840.302         8449.110
  8         11022.198         8643.456
  9         10814.650         8353.584
  10        10768.010         8279.469
  11        10809.986         8439.228
  12        10989.550         8561.106
  13        10863.622         8432.640
  14        10863.622         8467.227
  15        11061.842         8661.573
  16        10728.366         8299.233
  17        10805.322         8389.818
  18        10954.570         8521.578
  19        10884.610         8454.051  ,
      obj_value_avg_1  obj_value_het_1  obj_value_avg_2  obj_value_het_2  \
  0          3918.005         4024.011         9549.599         7131.015
  1          3902.535         4010.623         9511.893         7132.620
  2          3940.755         4050.081         9605.049         7198.425
  3          3910.725         4014.179         9531.855         7145.460
  4          3926.195         4030.423         9569.561         7192.005
  5          3925.285         4033.267         9567.343         7166.325
  6          3921.645         4023.417         9558.471         7172.745
  7          3892.525         3997.769         9487.495         7124.595
  8          3933.475         4036.075         9587.305         7209.660
  9          3909.815         4019.125         9529.637         7102.125
  10         3914.365         4021.755         9540.727         7143.855
  11         3896.165         3998.511         9496.367         7132.620
  12         3927.105         4032.317         9571.779         7174.350
  13         3909.815         4010.961         9529.637         7161.510
  14         3922.555         4024.931         9560.689         7182.375
  15         3929.835         4035.713         9578.433         7198.425
  16         3927.105         4032.869         9571.779         7193.610
  17         3936.205         4040.973         9593.959         7201.635
  18         3951.675         4054.557         9631.665         7254.600
  19         3928.015         4036.295         9573.997         7159.905

      obj_value_avg_3  obj_value_het_3
  0         10040.426         7317.621
  1         10000.782         7319.268
  2         10098.726         7386.795

In [5]:
# obj_value_df = pd.concat([output[0][0], output[1][0], output[2][0], output[3][0], output[4][0]], ignore_index = True)
# obj_value_df

In [ ]:
# objective value under rule better (do not change the weekly schedule if it is worse than the original schedule)
obj_value_better_df = pd.concat([output[0][1], output[1][1], output[2][1], output[3][1], output[4][1]], ignore_index = True)
obj_value_better_df

,obj_value_avg_1,obj_value_het_1,obj_value_avg_2,obj_value_het_2,obj_value_avg_3,obj_value_het_3
0,3915.275,4021.755,9542.945,7156.695,10033.430,7343.973
1,3916.185,4017.563,9545.163,7208.055,10035.762,7396.677
2,3911.635,4017.587,9534.073,7143.855,10024.102,7330.797
3,3928.015,4033.059,9573.997,7182.375,10066.078,7370.325
4,3902.535,4011.199,9511.893,7100.520,10000.782,7286.328
...,...,...,...,...,...,...
95,3912.545,4017.023,9536.291,7182.375,10026.434,7370.325
96,3931.655,4035.119,9582.869,7180.770,10075.406,7368.678
97,3920.735,4026.083,9556.253,7147.065,10047.422,7334.091
98,3948.035,4054.973,9622.793,7209.660,10117.382,7398.324
99,3921.645,4024.747,9558.471,7212.870,10049.754,7401.618

In [7]:
avg_work_day_sim = output[0][2] + output[1][2] + output[2][2] + output[3][2] + output[4][2]
avg_work_day_sim

[2.633047210300429,
 2.618271954674221,
 2.653486700215672,
 2.6327845382963493,
 2.6432664756446993,
 2.6402877697841727,
 2.627324749642346,
 2.6061036195883607,
 2.631200575125809,
 2.6216022889842634,
 2.6081370449678802,
 2.6539842067480257,
 2.6489208633093524,
 2.644396551724138,
 2.5825174825174826,
 2.6136363636363638,
 2.6153846153846154,
 2.636947218259629,
 2.6431146359048308,
 2.620443173695497,
 2.6421952957947257,
 2.6295503211991433,
 2.6051502145922747,
 2.6285919540229883,
 2.6551475881929445,
 2.6291814946619216,
 2.6221264367816093,
 2.5912305516265914,
 2.6464646464646466,
 2.608291636883488,
 2.6195965417867435,
 2.653179190751445,
 2.6379928315412187,
 2.6139105748757983,
 2.6446043165467628,
 2.640988372093023,
 2.593727726300784,
 2.6284697508896797,
 2.636039886039886,
 2.6140602582496415,
 2.619557458957887,
 2.661115133960898,
 2.655890804597701,
 2.645369705671213,
 2.617961511047755,
 2.6284896206156048,
 2.663761801016703,
 2.6523947750362846,
 2.6406585540443808,
 2.626876340243031,
 2.616642958748222,
 2.6284074605451937,
 2.6331658291457285,
 2.6207142857142856,
 2.612857142857143,
 2.6319595083152567,
 2.6324054246966453,
 2.603827072997874,
 2.6191155492154063,
 2.6226012793176974,
 2.606405693950178,
 2.619013581129378,
 2.6051687006460877,
 2.6343549536707056,
 2.615931721194879,
 2.626255380200861,
 2.632447954055994,
 2.6382521489971347,
 2.6211358734723222,
 2.6359743040685224,
 2.6115056818181817,
 2.6544540229885056,
 2.6331658291457285,
 2.635453895639743,
 2.638373751783167,
 2.6296028880866427,
 2.631054131054131,
 2.666907514450867,
 2.6179856115107913,
 2.6495664739884393,
 2.6485112563543938,
 2.6240981240981243,
 2.6281227694503926,
 2.6008462623413258,
 2.6623282718727403,
 2.6148936170212767,
 2.626068376068376,
 2.614672364672365,
 2.6458333333333335,
 2.6167023554603857,
 2.601139601139601,
 2.625714285714286,
 2.61423487544484,
 2.633670520231214,
 2.6541516245487364,
 2.6284074605451937,
 2.6252676659528906,
 2.6488824801730355,
 2.59585121602289,
 2.604122245913291]

In [8]:
improved_weeks_sim = output[0][3] + output[1][3] + output[2][3] + output[3][3] + output[4][3]
improved_weeks_sim

[83,
 86,
 91,
 91,
 92,
 90,
 84,
 89,
 78,
 79,
 82,
 94,
 83,
 78,
 91,
 85,
 77,
 85,
 84,
 88,
 93,
 89,
 84,
 84,
 93,
 91,
 89,
 85,
 81,
 80,
 80,
 84,
 99,
 89,
 83,
 82,
 81,
 92,
 82,
 83,
 89,
 88,
 84,
 90,
 95,
 82,
 79,
 91,
 77,
 85,
 94,
 87,
 87,
 82,
 86,
 77,
 87,
 83,
 84,
 88,
 78,
 83,
 86,
 94,
 99,
 87,
 86,
 92,
 83,
 85,
 89,
 97,
 85,
 85,
 91,
 84,
 90,
 79,
 83,
 90,
 87,
 79,
 97,
 87,
 85,
 96,
 84,
 83,
 87,
 85,
 82,
 86,
 81,
 79,
 96,
 85,
 85,
 89,
 83,
 87]

In [ ]:
# average_obj_value = pd.DataFrame({'obj_value_avg_1': obj_value_df['obj_value_avg_1'].sum()/100, 'obj_value_het_1': obj_value_df['obj_value_het_1'].sum()/100,
# 'obj_value_avg_2': obj_value_df['obj_value_avg_2'].sum()/100, 'obj_value_het_2': obj_value_df['obj_value_het_2'].sum()/100, 
# 'obj_value_avg_3': obj_value_df['obj_value_avg_3'].sum()/100, 'obj_value_het_3': obj_value_df['obj_value_het_3'].sum()/100}, index = [0])

# average_obj_value

,obj_value_avg_1,obj_value_het_1,obj_value_avg_2,obj_value_het_2,obj_value_avg_3,obj_value_het_3
0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
average_obj_value_better = pd.DataFrame({'obj_value_avg_1': obj_value_better_df['obj_value_avg_1'].sum()/100, 'obj_value_het_1': obj_value_better_df['obj_value_het_1'].sum()/100,
'obj_value_avg_2': obj_value_better_df['obj_value_avg_2'].sum()/100, 'obj_value_het_2': obj_value_better_df['obj_value_het_2'].sum()/100, 
'obj_value_avg_3': obj_value_better_df['obj_value_avg_3'].sum()/100, 'obj_value_het_3': obj_value_better_df['obj_value_het_3'].sum()/100}, index = [0])

average_obj_value_better

,obj_value_avg_1,obj_value_het_1,obj_value_avg_2,obj_value_het_2,obj_value_avg_3,obj_value_het_3
0,3925.1212,4030.21798,9566.94376,7178.15385,10058.66224,7365.99339

In [11]:
import numpy as np

avg_work_day_sim = np.array(avg_work_day_sim)
avg_work_day_result = np.mean(avg_work_day_sim)
avg_work_day_result

2.628656586626553

In [12]:
improved_weeks_sim = np.array(improved_weeks_sim)
improved_weeks_avg = np.average(improved_weeks_sim)
improved_weeks_avg

86.18

In [13]:
ori_obj_value_avg_1 = 0
ori_obj_value_avg_2 = 0
ori_obj_value_avg_3 = 0
ori_obj_value_het_1 = 0
ori_obj_value_het_2 = 0
ori_obj_value_het_3 = 0

for week in data_ori['weeknum'].unique():
    df_week = data_ori[data_ori['weeknum'] == week]
    for surgeon in df_week['surgeon'].unique():
        df_surgeon = df_week[df_week['surgeon'] == surgeon]
        _1, _2, _3, _4, _5, _6 = objective_cal(df_surgeon)
        
        ori_obj_value_avg_1 += _1
        ori_obj_value_avg_2 += _2
        ori_obj_value_avg_3 += _3
        ori_obj_value_het_1 += _4
        ori_obj_value_het_2 += _5
        ori_obj_value_het_3 += _6
    
ori_obj_value_df = pd.DataFrame({'ori_obj_value_avg_1': ori_obj_value_avg_1, 'ori_obj_value_het_1': ori_obj_value_het_1, 'ori_obj_value_avg_2': ori_obj_value_avg_2,'ori_obj_value_het_2': ori_obj_value_het_2, 'ori_obj_value_avg_3': ori_obj_value_avg_3, 'ori_obj_value_het_3': ori_obj_value_het_3}, index = [0])
ori_obj_value_df

,ori_obj_value_avg_1,ori_obj_value_het_1,ori_obj_value_avg_2,ori_obj_value_het_2,ori_obj_value_avg_3,ori_obj_value_het_3
0,4124.575,4240.775,10053.085,7594.86,10569.79,7793.604

In [14]:
import pandas as pd


# Create the DataFrame
res = {
    ' ': ['OR time', '(in hours)', 'Post-LOS', '(in days)', 'ICU Time', '(in days)'],
    'Effect': ['Avg', 'Het', 'Avg', 'Het', 'Avg', 'Het'],
    'dst_orig': ori_obj_value_df.values.flatten(),
    'dst': average_obj_value_better.values.flatten(),
    'delta': (ori_obj_value_df.values.flatten() - average_obj_value_better.values.flatten()),
    'rel_decr': (ori_obj_value_df.values.flatten() - average_obj_value_better.values.flatten()) / ori_obj_value_df.values.flatten(),
    'improve_week': pd.Series([improved_weeks_avg] * 6),
    'avg_work_day': pd.Series([avg_work_day_result] * 6)
}

res_df = pd.DataFrame(res)
res_df
res_df['dst_orig'] = res_df['dst_orig'].round(2)
res_df['dst'] = res_df['dst'].round(2)
res_df['delta'] = res_df['delta'].round(2)
res_df['rel_decr'] = (res_df['rel_decr'] * 100).round(2).astype(str) + '%'
res_df['avg_work_day'] = res_df['avg_work_day'].round(3)
res_df['improve_week'] = res_df['improve_week'].round(0)

# Save to Excel
res_df.to_excel(f'res/output_stochastic_random_{int(frac*100)}urgent_better.xlsx', index = False)